import {
  Affix,
  Alert,
  Anchor,
  App,
  AutoComplete,
  Avatar,
  Badge,
  BorderBeam,
  Breadcrumb,
  Button,
  Calendar,
  Card,
  Carousel,
  Cascader,
  Checkbox,
  Collapse,
  ColorPicker,
  ConfigProvider,
  DatePicker,
  Descriptions,
  Divider,
  Drawer,
  Dropdown,
  Empty,
  Flex,
  FloatButton,
  Form,
  Image,
  Input,
  InputNumber,
  Layout,
  List,
  Masonry,
  Mentions,
  Menu,
  Modal,
  Pagination,
  Popconfirm,
  Popover,
  Progress,
  QRCode,
  Radio,
  Rate,
  Result,
  Row,
  Segmented,
  Select,
  Skeleton,
  Slider,
  Space,
  Spin,
  Splitter,
  Statistic,
  Steps,
  Switch,
  Table,
  Tabs,
  Tag,
  TimePicker,
  Timeline,
  Tooltip,
  Tour,
  Transfer,
  Tree,
  TreeSelect,
  Typography,
  Upload,
  Watermark,
} from "antd";
import { createElement, type ElementType, type ReactNode } from "react";

type Renderer = (
  props: Record<string, unknown>,
  children: ReactNode[],
) => ReactNode;

const component = (target: ElementType): Renderer => {
  const renderComponent = (
    props: Record<string, unknown>,
    children: ReactNode[],
  ) =>
    children.length
      ? createElement(target, props, children)
      : createElement(target, props);
  return renderComponent;
};

const alertProjection = (
  props: Record<string, unknown>,
  children: ReactNode[],
) => {
  const message =
    typeof props.message === "string" || typeof props.message === "number"
      ? props.message
      : children;
  return createElement(Alert, { ...props, message });
};

const renderers: Record<string, Renderer> = {
  "ui.button": component(Button),
  "ui.float-button": component(FloatButton),
  "ui.icon": component("span"),
  "ui.typography": component(Typography),
  "ui.divider": component(Divider),
  "ui.flex": component(Flex),
  "ui.grid": component(Row),
  "ui.layout": component(Layout),
  "ui.masonry": component(Masonry),
  "ui.space": component(Space),
  "ui.splitter": component(Splitter),
  "ui.anchor": component(Anchor),
  "ui.breadcrumb": component(Breadcrumb),
  "ui.dropdown": component(Dropdown),
  "ui.menu": component(Menu),
  "ui.pagination": component(Pagination),
  "ui.steps": component(Steps),
  "ui.tabs": component(Tabs),
  "ui.auto-complete": component(AutoComplete),
  "ui.cascader": component(Cascader),
  "ui.checkbox": component(Checkbox),
  "ui.color-picker": component(ColorPicker),
  "ui.date-picker": component(DatePicker),
  "ui.form": component(Form),
  "ui.input": component(Input),
  "ui.input-number": component(InputNumber),
  "ui.mentions": component(Mentions),
  "ui.radio": component(Radio),
  "ui.rate": component(Rate),
  "ui.select": component(Select),
  "ui.slider": component(Slider),
  "ui.switch": component(Switch),
  "ui.time-picker": component(TimePicker),
  "ui.transfer": component(Transfer),
  "ui.tree-select": component(TreeSelect),
  "ui.upload": component(Upload),
  "ui.avatar": component(Avatar),
  "ui.badge": component(Badge),
  "ui.calendar": component(Calendar),
  "ui.card": component(Card),
  "ui.carousel": component(Carousel),
  "ui.collapse": component(Collapse),
  "ui.descriptions": component(Descriptions),
  "ui.empty": component(Empty),
  "ui.image": component(Image),
  "ui.list": component(List),
  "ui.popover": component(Popover),
  "ui.qr-code": component(QRCode),
  "ui.segmented": component(Segmented),
  "ui.statistic": component(Statistic),
  "ui.table": component(Table),
  "ui.tag": component(Tag),
  "ui.timeline": component(Timeline),
  "ui.tooltip": component(Tooltip),
  "ui.tour": component(Tour),
  "ui.tree": component(Tree),
  "ui.alert": component(Alert),
  "ui.drawer": component(Drawer),
  "ui.message": alertProjection,
  "ui.modal": component(Modal),
  "ui.notification": alertProjection,
  "ui.popconfirm": component(Popconfirm),
  "ui.progress": component(Progress),
  "ui.result": component(Result),
  "ui.skeleton": component(Skeleton),
  "ui.spin": component(Spin),
  "ui.watermark": component(Watermark),
  "ui.affix": component(Affix),
  "ui.app": component(App),
  "ui.border-beam": component(BorderBeam),
  "ui.config-provider": component(ConfigProvider),
  "ui.util": component("span"),
};

const legacyTagFor = (tag: string) =>
  `ui.${tag === "QRCode" ? "qr-code" : tag.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase()}`;

export const renderAntDesignComponent = (
  tag: string,
  props: Record<string, unknown>,
  children: ReactNode[],
): ReactNode | null =>
  (renderers[tag] ?? renderers[legacyTagFor(tag)])?.(props, children) ?? null;
