/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type JsonValue =
  | null
  | boolean
  | number
  | string
  | JsonValue[]
  | {
      [k: string]: JsonValue;
    };
export type Node = {
  [k: string]: unknown;
} & {
  id: Id;
  kind: "element" | "text" | "image" | "component";
  name: string;
  tag: string;
  packageName?: string;
  defaultModule?: boolean;
  style: Style;
  layout?: FlexLayout;
  layoutItem?: FlexItem;
  computedLayout?: ComputedLayout;
  props: JsonObject;
  children: Node[];
  responsive?: {
    [k: string]: ResponsiveLayout;
  };
  text?: string;
  assetId?: Id;
  alt?: string;
  source?: Source;
};
export type StyleValue = number | string | boolean;
export type Sizing =
  | {
      mode: "fixed";
      value: number;
    }
  | {
      mode: "fill";
    }
  | {
      mode: "hug";
    }
  | {
      mode: "minmax";
      min: number;
      max?: number;
    };

export interface DesignDocumentV2 {
  $schema?: string;
  version: "2.0.0";
  id: Id;
  name: string;
  designSystem: DesignSystem;
  assets: {
    [k: string]: Asset;
  };
  root: Node;
}
export interface DesignSystem {
  id: Id;
  version: string;
  digest: string;
  tokens: JsonObject;
  components: {
    [k: string]: Component;
  };
  allowedTags?: string[];
}
export interface JsonObject {
  [k: string]: JsonValue;
}
export interface Component {
  id: Id;
  packageName?: string;
  defaultModule?: boolean;
  propsSchema?: JsonObject;
  variants?: {
    [k: string]: string[];
  };
  slots?: {
    [k: string]: {
      type: "string" | "text" | "node" | "nodes";
      required?: boolean;
    };
  };
}
export interface Asset {
  id: Id;
  type: "image" | "icon" | "font" | "file";
  src: string;
  mimeType: string;
  hash?: string;
  width?: number;
  height?: number;
  alt?: string;
}
export interface Style {
  display?: "block" | "inline" | "inline-block" | "flex" | "inline-flex" | "none" | "-webkit-box";
  position?: "static" | "relative" | "absolute" | "fixed" | "sticky";
  top?: StyleValue;
  right?: StyleValue;
  bottom?: StyleValue;
  left?: StyleValue;
  boxSizing?: "content-box" | "border-box";
  width?: StyleValue;
  height?: StyleValue;
  minWidth?: StyleValue;
  minHeight?: StyleValue;
  maxWidth?: StyleValue;
  maxHeight?: StyleValue;
  padding?: StyleValue;
  paddingTop?: StyleValue;
  paddingRight?: StyleValue;
  paddingBottom?: StyleValue;
  paddingLeft?: StyleValue;
  margin?: StyleValue;
  marginTop?: StyleValue;
  marginRight?: StyleValue;
  marginBottom?: StyleValue;
  marginLeft?: StyleValue;
  background?: string;
  backgroundColor?: string;
  backgroundImage?: string;
  backgroundPosition?: string;
  backgroundSize?: string;
  backgroundRepeat?: "repeat" | "no-repeat";
  backgroundClip?: string;
  border?: string;
  borderTopWidth?: number;
  borderRightWidth?: number;
  borderBottomWidth?: number;
  borderLeftWidth?: number;
  borderTopColor?: string;
  borderRightColor?: string;
  borderBottomColor?: string;
  borderLeftColor?: string;
  borderStyle?: "solid" | "dashed" | "dotted" | "none";
  borderRadius?: StyleValue;
  borderTopLeftRadius?: StyleValue;
  borderTopRightRadius?: StyleValue;
  borderBottomRightRadius?: StyleValue;
  borderBottomLeftRadius?: StyleValue;
  outlineWidth?: number;
  outlineColor?: string;
  outlineStyle?: "solid" | "dashed" | "dotted" | "none";
  color?: string;
  fontSize?: number;
  fontFamily?: string;
  fontWeight?: number;
  fontStyle?: "normal" | "italic";
  lineHeight?: StyleValue;
  letterSpacing?: StyleValue;
  textAlign?: "left" | "right" | "center" | "justify";
  textTransform?: "none" | "uppercase" | "lowercase";
  textDecoration?: "none" | "underline" | "line-through";
  textOverflow?: "clip" | "ellipsis";
  whiteSpace?: "normal" | "nowrap" | "pre" | "pre-wrap";
  flexGrow?: number;
  flexShrink?: number;
  flexBasis?: StyleValue;
  flexDirection?: "row" | "column" | "row-reverse" | "column-reverse";
  flexWrap?: "nowrap" | "wrap" | "wrap-reverse";
  justifyContent?: "flex-start" | "flex-end" | "center" | "space-between" | "space-around" | "space-evenly";
  alignItems?: "flex-start" | "flex-end" | "center" | "baseline" | "stretch";
  alignSelf?: "auto" | "flex-start" | "flex-end" | "center" | "baseline" | "stretch";
  alignContent?: "flex-start" | "flex-end" | "center" | "space-between" | "stretch";
  columnGap?: number;
  rowGap?: number;
  opacity?: number;
  zIndex?: number;
  transform?: string;
  boxShadow?: string;
  backdropFilter?: string;
  filter?: string;
  overflow?: "visible" | "hidden" | "scroll" | "auto";
  overflowX?: "visible" | "hidden" | "scroll" | "auto";
  overflowY?: "visible" | "hidden" | "scroll" | "auto";
}
export interface FlexLayout {
  mode: "flex" | "absolute";
  direction?: "row" | "row-reverse" | "column" | "column-reverse";
  justifyContent?: "flex-start" | "flex-end" | "center" | "space-between" | "space-around" | "space-evenly";
  alignItems?: "stretch" | "flex-start" | "flex-end" | "center" | "baseline";
  wrap?: "nowrap" | "wrap" | "wrap-reverse";
  gap?: number;
  rowGap?: number;
  columnGap?: number;
  padding?: EdgeInsets;
}
export interface EdgeInsets {
  top?: number;
  right?: number;
  bottom?: number;
  left?: number;
}
export interface FlexItem {
  width?: Sizing;
  height?: Sizing;
  flex?:
    | number
    | string
    | {
        grow?: number;
        shrink?: number;
        basis?: StyleValue;
      };
  flexGrow?: number;
  flexShrink?: number;
  flexBasis?: StyleValue;
  alignSelf?: "auto" | "flex-start" | "flex-end" | "center" | "baseline" | "stretch";
  margin?: EdgeInsets;
  position?: "flow" | "absolute";
  inset?: EdgeInsets;
}
export interface ComputedLayout {
  x: number;
  y: number;
  width: number;
  height: number;
  contentWidth?: number;
  contentHeight?: number;
  mainSize?: number;
  crossSize?: number;
  lineIndex?: number;
  resolvedGap?: number;
  margin?: EdgeInsets;
  padding?: EdgeInsets;
}
export interface ResponsiveLayout {
  minWidth?: number;
  maxWidth?: number;
  direction?: "row" | "row-reverse" | "column" | "column-reverse";
  justifyContent?: "flex-start" | "flex-end" | "center" | "space-between" | "space-around" | "space-evenly";
  alignItems?: "stretch" | "flex-start" | "flex-end" | "center" | "baseline";
  wrap?: "nowrap" | "wrap" | "wrap-reverse";
  flexWrap?: "nowrap" | "wrap" | "wrap-reverse";
  gap?: number;
  rowGap?: number;
  columnGap?: number;
  padding?: EdgeInsets;
  layout?: FlexLayout;
  layoutItem?: FlexItem;
  computedLayout?: ComputedLayout;
  sizing?: "fixed" | "fill" | "hug" | "minmax";
  visible?: boolean;
}
export interface Source {
  tool?: string;
  type?: string;
  id?: string;
}
